databases:
  - name: mandtbank
    databaseName: mandtbank
    user: mandtbank

services:
  - type: web
    name: mandtbank
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -b 0.0.0.0 backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mandtbank
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4