# databases:
#   - name: mandtbank
#     databaseName: mandtbank
#     user: mandtbank
#     plan: free

services:
  - type: web
    name: mandtbank
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -b 0.0.0.0 backend.wsgi:application"
    plan: free
