# Generated by Django 3.2.18 on 2023-09-08 20:01

from django.db import migrations, models
import pockets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='bg_img',
            field=models.ImageField(blank=True, upload_to=pockets.models.upload_to),
        ),
    ]
