# Generated by Django 4.2 on 2023-04-25 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[['Debit', 'Debit'], ['Credit', 'Credit']], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[['Completed', 'Completed'], ['canceled', 'canceled'], ['pending', 'pending'], ['failed', 'failed']], max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
