# Generated by Django 4.2 on 2023-05-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[['Completed', 'Completed'], ['canceled', 'canceled'], ['pending', 'pending'], ['failed', 'failed']], default='pending', max_length=50),
        ),
    ]
