# Generated by Django 4.2 on 2023-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
