# Generated by Django 4.2 on 2023-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_activity_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='routine_nunmber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
